set nocompatible " use Vim mode instead of pure Vi, it must be the first instruction

set showcmd
set incsearch           " search as characters are entered
set hlsearch            " highlight matches

if has('mouse')
  set mouse=a
endif
