# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

alias h=history
alias hg="history | grep "
alias hh=hstr
alias la="ls -a"
alias lt="ls -altr"
